### ISSUE TITLE
Adicionar flag para indicar o arquivo de configuração

### ISSUE THREAD

**Issue by jasondavindev** [jasondavindev/live-reload-go#19]
Pensando em que o usuário pode pegar apenas o binário dessa aplicação, quando for rodar o binário irá lançar uma excessão porque o arquivo de configuração não existe.

# Solução
Criar uma flag `-config-file=path_aqui`

Fluxo: antes de ler o arquivo config.yml e instanciar as configs, criar uma função intermediário que verifique se foi passado a flag `-config-file` e o valor foi diferente de vazio. Se for diferente de vazio passa a string adiante, senão passa o valor `config.yml`

Exemplo:
```go
...
flagValue := pegaFlagConfigFile()
configFilePath := flagValue == "" ? "config.yml" : flagValue
CfgFactory(configFilePath)

func CfgFactory(configFilePath string) Config {
	yamlFile, err := ioutil.ReadFile(configFilePath)
        ...
        ...
        ...
}
```

**Comment by NicolasFujisawa** [comment]
@jasondavindev A flag seria para verificar existe um arquivo de configuração quando estiver executando o programa?
